version: '3.2'
services:
  traefik:
    image: traefik
    command:
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=docker.localhost"
      - "--docker.watch"
      - "--logLevel=DEBUG"
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.prod.toml:/traefik.toml
      - ./traefik/acme.json:/etc/traefik/acme.json
    depends_on:
      - api
      - client
      - oauthflow
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: 128m
    environment:
      - DO_AUTH_TOKEN=6d632f63cd5f03eba61659e19e0f9264e1d6854d42562b54396c48362dcb3415
    labels:
    - "traefik.backend=traefik"
    - "traefik.enable=true"
    - "traefik.logLevel=DEBUG"
    - "traefik.port=8080"
    - "traefik.passHostHeader=true"
    - "traefik.frontend.entryPoints=http"
    - "traefik.backend.loadbalancer.method=wrr"
    - "traefik.backend.loadbalancer.swarm=true"
    networks:
      - web
  api:
    image: saulable/produktivv_server
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: 512m
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.backend=api"
        - "traefik.port=5000"
        - "traefik.frontend.rule=Host:www.produktivv.com; PathPrefix:/api"
        - "traefik.frontend.passHostHeader=true"
    ports:
      - '5000'
    networks:
      - web
    secrets:
      - mongoURI
    environment:
      NODE_ENV: "production"
  oauthflow:
    image: saulable/produktivv_oauth
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 128m
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.backend=oauthflow"
        - "traefik.port=5050"
        - "traefik.frontend.rule=Host:oauth.produktivv.com"
        - "traefik.frontend.passHostHeader=true"
    ports:
      - '5050'
    networks:
      - web
    secrets:
      - mongoURI
      - fb_client
      - fb_secret
      - fb_cb_url
      - google_client
      - google_secret
    environment:
      NODE_ENV: "production"
  client:
    image: saulable/produktivv_client
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 56m
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.backend=client"
        - "traefik.frontend.rule=Host:www.produktivv.com"
    ports:
      - "3000"
    networks:
      - web
  nginx:
    image: schmunk42/nginx-redirect
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.05"
          memory: 56m
      labels:
        - "traefik.docker.network=web"
        - "traefik.backend=nginx"
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:produktivv.com"
    environment:
      - SERVER_REDIRECT=www.produktivv.com
      - SERVER_REDIRECT_SCHEME=https
    networks:
    - web
secrets:
  mongoURI:
    file: ./secrets/mongo_uri.txt
  fb_client:
    file: ./secrets/fb_client_id.txt
  fb_secret:
    file: ./secrets/fb_secret_id.txt
  fb_cb_url:
    file: ./secrets/fb_callback_url.txt
  google_client:
    file: ./secrets/google_client_id.txt
  google_secret:
    file: ./secrets/google_client_secret.txt
networks:
  web:
    external: true