version: '3'
services:
  traefik:
    image: traefik
    command: --web --docker
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    image: produktivv_server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '5000'
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host:server.produktivv.com"
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    image: produktivv_client
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - web
    ports:
      - '3000'
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:client.produktivv.com"
networks:
  web:
    driver: overlay
