version: '3.2'
services:
  traefik:
    networks:
      - web
    image: traefik:1.7.2-alpine
    command:
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=docker.localhost"
      - "--docker.watch"
      - "--logLevel=DEBUG"
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.dev.toml:/traefik.toml
      - ./traefik/certs/:/certs/
    depends_on:
      - api
      - client
      - oauthflow
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: 128m
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    image: saulable/produktivv_server
    volumes:
      - /app/node_modules
      - ./server:/app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512m
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.backend=api"
        - "traefik.port=5000"
        - "traefik.frontend.rule=Host:localhost; PathPrefix:/api"
        - "traefik.frontend.passHostHeader=true"
    ports:
      - '5000'
    networks:
      - web
    secrets:
      - mongoURI
    environment:
      NODE_ENV: "production"
  oauthflow:
    build:
      dockerfile: Dockerfile.dev
      context: ./oauthflow
    image: saulable/produktivv_oauth
    volumes:
      - /app/node_modules
      - ./oauthflow:/app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 128m
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web"
        - "traefik.backend=oauthflow"
        - "traefik.port=5050"
        - "traefik.frontend.rule=Host:localhost; PathPrefix:/auth"
        - "traefik.frontend.passHostHeader=true"
    ports:
      - '5050'
    networks:
      - web
    secrets:
      - mongoURI
      - fb_client
      - fb_secret
      - fb_cb_url
      - google_client
      - google_secret
    environment:
      NODE_ENV: "production"
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    image: saulable/produktivv_client
    volumes:
      - /app/node_modules
      - ./client:/app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 128m
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.backend=client"
        - "traefik.frontend.rule=Host:localhost"
    ports:
      - "3000"
    networks:
      - web
secrets:
  mongoURI:
    file: ./secrets/mongo_uri.txt
  fb_client:
    file: ./secrets/fb_client_id.txt
  fb_secret:
    file: ./secrets/fb_secret_id.txt
  fb_cb_url:
    file: ./secrets/fb_callback_url.txt
  google_client:
    file: ./secrets/google_client_id.txt
  google_secret:
    file: ./secrets/google_client_secret.txt
networks:
  web:
    external: true
