defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
  [entryPoints.dashboard]
    address=":8080"

[retry]

[api]
entrypoint = "dashboard"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "produktivv.com"
watch = true
exposedbydefault = false

[acme]
email = "hello@youtech.io"
entryPoint = "https"
storage = "/etc/traefik/acme.json"
acmeLogging = true
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [acme.dnsChallenge]
  provider = "digitalocean"
  delayBeforeCheck = 0
  [acme.httpChallenge]
  entryPoint = "http"
  [[acme.domains]]
    main = "*.produktivv.com"
    sans = ["produktivv.com"]
    
